CREATE TABLE `lead_assignments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`subscriptionId` varchar(128) NOT NULL,
	`customerId` varchar(128),
	`customerName` varchar(256),
	`email` varchar(320),
	`phone` varchar(64),
	`leadCategory` varchar(32) DEFAULT 'subscription',
	`leadType` varchar(64),
	`planName` varchar(256),
	`billingCycles` int DEFAULT 0,
	`cyclesCompleted` int DEFAULT 0,
	`totalSpend` float DEFAULT 0,
	`monthlyAmount` float DEFAULT 0,
	`currencyCode` varchar(8) DEFAULT 'GBP',
	`billingStatus` varchar(32),
	`retryAttempts` int DEFAULT 0,
	`urgencyScore` int DEFAULT 0,
	`urgencyFlags` text,
	`eventDate` varchar(32),
	`assignedAgent` varchar(128),
	`assignedAt` float,
	`workStatus` varchar(32) DEFAULT 'new',
	`statusChangedAt` float,
	`managerNote` text,
	`agentNote` text,
	`attemptCount` int DEFAULT 0,
	`noAnswerCount` int DEFAULT 0,
	`lastCallAt` float,
	`lastCallResult` varchar(32),
	`callbackAt` float,
	`followUpAt` float,
	`followUpNote` text,
	`lastTransactionDate` varchar(32),
	`lastShipmentDate` varchar(32),
	`cancelledAt` varchar(32),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lead_assignments_id` PRIMARY KEY(`id`),
	CONSTRAINT `lead_assignments_subscriptionId_unique` UNIQUE(`subscriptionId`)
);
--> statement-breakpoint
CREATE TABLE `call_attempts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`subscriptionId` varchar(128) NOT NULL,
	`agentName` varchar(128),
	`result` varchar(32),
	`note` text,
	`callbackAt` float,
	`followUpAt` float,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `call_attempts_id` PRIMARY KEY(`id`)
);
