CREATE TABLE retention_deals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  contactId INT NOT NULL,
  agentName VARCHAR(256) NOT NULL,
  dealType ENUM('subscription', 'installment') NOT NULL,
  instMode ENUM('equal', 'custom') DEFAULT NULL,
  stripeCustomerId VARCHAR(128) DEFAULT NULL,
  stripeScheduleId VARCHAR(128) DEFAULT NULL,
  stripeSubscriptionIds JSON DEFAULT NULL,
  totalAmount DECIMAL(10, 2) NOT NULL,
  deposit DECIMAL(10, 2) DEFAULT 0,
  paymentCount INT DEFAULT NULL,
  billingCycle INT DEFAULT NULL,
  products JSON NOT NULL,
  freeGifts JSON DEFAULT NULL,
  payments JSON DEFAULT NULL,
  shipDate VARCHAR(32) DEFAULT NULL,
  isFutureDeal BOOLEAN DEFAULT FALSE,
  cardLast4 VARCHAR(4) DEFAULT NULL,
  mintsoftOrderId INT DEFAULT NULL,
  mintsoftOrderNumber VARCHAR(128) DEFAULT NULL,
  status ENUM('pending', 'active', 'future', 'failed', 'cancelled') NOT NULL DEFAULT 'pending',
  notes TEXT DEFAULT NULL,
  createdAt BIGINT NOT NULL,
  updatedAt BIGINT NOT NULL,
  INDEX idx_retention_deals_contactId (contactId),
  INDEX idx_retention_deals_status (status),
  INDEX idx_retention_deals_stripeScheduleId (stripeScheduleId),
  -- stripeSubscriptionIds is JSON, no index needed
);
